language: minimal
if: head_branch =~ ^beta_update$ OR branch = beta
  
before_install:

script:
  #- export CSRID='git log --format=%B -n 1 $(git rev-parse @~)' && openssl req -in ./csr-list/${CSRID}.csr -noout -text
  - git log && git branch
  - CSR_COMMIT_ID=$(git rev-parse HEAD~1) && echo ${CSR_COMMIT_ID} && git log --format=%B -n 1 ${CSR_COMMIT_ID}
  
#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push enterpriseconnect/agent:v1
#    on:
#      branch: v1_oci_spec

#after_deploy: docker rmi enterpriseconnect/agent:v1 -f && docker run -it enterpriseconnect/agent:v1 ./agent -ver

notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    on_success: always  
    on_failure: always
