language: minimal
if: head_branch =~ ^beta_update$ OR branch = beta
  
before_install:

script:
  #- export CSRID='git log --format=%B -n 1 $(git rev-parse @~)' && openssl req -in ./csr-list/${CSRID}.csr -noout -text
  - export CSR_FILE=$(git log --all --format=%B --grep='.csr' -n 1)
  - openssl req -in ./csr-list/${CSR_FILE} -noout -subject
  - openssl req -in ./csr-list/${CSR_FILE} -noout -text | grep -Po '(?<=email:).*?(, )'
  
#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push enterpriseconnect/agent:v1
#    on:
#      branch: v1_oci_spec

#after_deploy: docker rmi enterpriseconnect/agent:v1 -f && docker run -it enterpriseconnect/agent:v1 ./agent -ver

notifications:
  slack: enterprisecon-j2w6229:XE0ViHsIgL4oQ27464Hq01hO:general
  email:  
    recipients:  
    - ec-research@ge.com
    on_success: always  
    on_failure: always
