name: beta-ca-ci
on:
  push:
    branches: [ beta ]
  pull_request:
    branches: [ beta ]
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: beta
    env:
      #AGENT_REV: "1.2-b.0.reiwa"
      AGENT_REV: "temp"
    steps:
      - uses: actions/checkout@v2
      - name: pr merged
        if: github.event_name == 'push'
        id: pr-merged
        run: |
          chmod 775 deploy.sh && source ./deploy.sh
