name: beta-hash-gen
on:
  workflow_dispatch:
    inputs:
      Id:
        description: 'The Id which was assigned originally to the owner of the license'
        required: true
      PPS:
        description: 'The passphrase used for this license'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: beta
    env:
      #AGENT_REV: "1.2-b.0.reiwa"
      AGENT_REV: "temp"
    steps:
      - uses: actions/checkout@v2
      - name: Generate a owner hash
        id: gen-owner-hash
        env:
          lic_id: ${{ github.event.inputs.Id }}
          lic_pps: ${{ github.event.inputs.PPS }}
          EC_PPRS: ${{ secrets.ADM_PPS }}
          EC_PVK: ${{ secrets.ADM_KEY }}
          EC_PBK: ${{ secrets.ADM_CER }}
          EC_TKN: ${{ secrets.ADM_TKN }}
        run: |
          chmod 644 ./hash-gen.sh
          source ./hash-gen.sh
      - name: Send hash via email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.ADM_EML_SVR }}
          server_port: 587
          username: ${{secrets.ADM_EML_USR}}
          password: ${{secrets.ADM_EML_PWD}}
          subject: EC-Release > Certifactory > License
          # Literal body:
          body: |
            ### Owner Hash Generation
            Upon the request, a copy of the owner's as follows-
            
            ${{env.LIC_HSH}}
            
            The hash is only valid for 90 days. As the owner of this license, you may continue come back at anytime to renew this hash via the workflow process.
            
            <sup>This hash is not sharable or transferrable, and not being stored anywhere in our system.</sup>
          # Read file contents as body:
          to: ${{ env.lic_email }}
          from: EC Autobot <ec.autobot@outlook.com>
          # Optional carbon copy recipients
          #cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients
          #bcc: r2d2@example.com,hansolo@example.com
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          #attachments: attachments.zip,git.diff,./dist/static/main.js
