name: release-ca-ci
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
    types: [opened, synchronize]
  workflow_dispatch:  
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: release
    #env:
    steps:
      - uses: actions/checkout@v2
      - name: bootstrap release
        id: bootstrap
        #env:
        run: |
          echo bootstrap release
      - name: pr merged
        if: github.event_name == 'push'
        id: pr-merged
        run: |
          echo pr has been merged and closed
        
        
        
        
      
      
          
